<?xml version="1.0" encoding="utf-8"?>
<test-run id="2" name="Reflection.Randomness.exe" fullname="C:/MyRepo/Reflection.Randomness/Reflection.Randomness.csproj/bin/Debug/Reflection.Randomness.exe" testcasecount="1" result="Failed" start-time="2018-06-06 19:54:31Z" end-time="2018-06-06 19:54:31Z" duration="0.193523" total="1" passed="0" failed="1" inconclusive="0" skipped="0" asserts="1" random-seed="1903013349">
  <command-line><![CDATA["C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\bin\Debug\Reflection.Randomness.exe"   ]]></command-line>
  <filter />
  <test-suite type="Assembly" id="1002" name="Reflection.Randomness.exe" fullname="C:/MyRepo/Reflection.Randomness/Reflection.Randomness.csproj/bin/Debug/Reflection.Randomness.exe" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2018-06-06 19:54:31Z" end-time="2018-06-06 19:54:31Z" duration="0.193523" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="1">
    <environment framework-version="3.6.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\bin\Debug" machine-name="DESKTOP-MJHFLF4" user="altuk" user-domain="DESKTOP-MJHFLF4" culture="en-US" uiculture="en-US" os-architecture="x86" />
    <settings>
      <setting name="WorkDirectory" value="C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\bin\Debug" />
      <setting name="NumberOfTestWorkers" value="4" />
    </settings>
    <properties>
      <property name="_PID" value="11384" />
      <property name="_APPDOMAIN" value="Reflection.Randomness.exe" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="1003" name="Reflection" fullname="Reflection" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2018-06-06 19:54:31Z" end-time="2018-06-06 19:54:31Z" duration="0.153974" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="1">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="1004" name="Randomness" fullname="Reflection.Randomness" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2018-06-06 19:54:31Z" end-time="2018-06-06 19:54:31Z" duration="0.150775" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="1">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="1000" name="Generator_should" fullname="Reflection.Randomness.Generator_should" classname="Reflection.Randomness.Generator_should" runstate="Runnable" testcasecount="1" result="Failed" site="Child" start-time="2018-06-06 19:54:31Z" end-time="2018-06-06 19:54:31Z" duration="0.139552" total="1" passed="0" failed="1" warnings="0" inconclusive="0" skipped="0" asserts="1">
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="1001" name="FailWithInformativeMessage_OnIncorrectAttributeUsage" fullname="Reflection.Randomness.Generator_should.FailWithInformativeMessage_OnIncorrectAttributeUsage" methodname="FailWithInformativeMessage_OnIncorrectAttributeUsage" classname="Reflection.Randomness.Generator_should" runstate="Runnable" seed="708897621" result="Failed" start-time="2018-06-06 19:54:31Z" end-time="2018-06-06 19:54:31Z" duration="0.102590" asserts="1">
            <failure>
              <message><![CDATA[  Expected: <System.ArgumentException>
  But was:  <System.TypeInitializationException: The type initializer for 'Reflection.Randomness.Generator`1' threw an exception. ---> System.ArgumentException: T3
   at Reflection.Randomness.Generator`1..cctor() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator.cs:line 42
   --- End of inner exception stack trace ---
   at Reflection.Randomness.Generator`1..ctor() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator.cs:line 36
   at Reflection.Randomness.Generator_should.<>c.<FailWithInformativeMessage_OnIncorrectAttributeUsage>b__4_0() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator_should.cs:line 128
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>
]]></message>
              <stack-trace><![CDATA[at Reflection.Randomness.Generator_should.FailWithInformativeMessage_OnIncorrectAttributeUsage() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator_should.cs:line 128
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: <System.ArgumentException>
  But was:  <System.TypeInitializationException: The type initializer for 'Reflection.Randomness.Generator`1' threw an exception. ---> System.ArgumentException: T3
   at Reflection.Randomness.Generator`1..cctor() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator.cs:line 42
   --- End of inner exception stack trace ---
   at Reflection.Randomness.Generator`1..ctor() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator.cs:line 36
   at Reflection.Randomness.Generator_should.<>c.<FailWithInformativeMessage_OnIncorrectAttributeUsage>b__4_0() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator_should.cs:line 128
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>
]]></message>
                <stack-trace><![CDATA[at Reflection.Randomness.Generator_should.FailWithInformativeMessage_OnIncorrectAttributeUsage() in C:\MyRepo\Reflection.Randomness\Reflection.Randomness.csproj\Generator_should.cs:line 128
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>